#!/usr/bin/env python
# -*- coding: utf-8 -*-

import inspect
import logging
import argparse

from pyoscilloskop.webapp import RigolPlugin, api, interface, DEFAULT_CONTEXT 

logger = logging.getLogger(__name__)

def main():
    #global DEFAULT_CONTEXT
    parser = argparse.ArgumentParser( 
      description='Run a web servers for your Rigol Scope' )
    parser.add_argument('-p', '--port', type=int, default=8080,
      help='The port to run the web server on.')
    parser.add_argument('-6', '--ipv6', action='store_true',
      help='Listen to incoming connections via IPv6 instead of IPv4.')
    parser.add_argument('-d', '--debug', action='store_true',
      help='Start in debug mode.')
    parser.add_argument('--scope-name', help='Name of the oscilloscope to display.')
    parser.add_argument('--backend', default='linux_kernel', help='The backend to use')
    parser.add_argument('device', help='The /dev/usbtmc0 -like device name.')
    args = parser.parse_args()

    if args.debug:
        logging.basicConfig(level=logging.DEBUG)

    if args.scope_name : DEFAULT_CONTEXT['scope_name'] = args.scope_name

    if args.backend not in ('linux_kernel', 'tcp_socket', 'python_usbtmc'):
        parser.error('Please select a valid backend')

    api.install(RigolPlugin(args.device, backend=args.backend))
    interface.mount('/api', api)
    app = interface

    if args.ipv6:
        app.run(host='::', server='cherrypy', port=args.port)
    else:
        app.run(host='0.0.0.0', server='cherrypy', port=args.port, debug=True)

if __name__ == '__main__':
    main()

